# Generated by Django 2.2.26 on 2022-09-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0029_auto_20210202_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorFocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifier')),
                ('description', models.TextField(verbose_name='Description')),
                ('url_auth', models.CharField(help_text='URL d''authentification pour aller chercher le token', max_length=128, verbose_name='URL d''authentification')),
                ('client_id', models.CharField(help_text='Client ID pour l''API', max_length=128, verbose_name='Client ID')),
                ('client_secret', models.CharField(help_text='Mot de passe pour avoir le token de l''API', max_length=1024, verbose_name='Client Secret')),
                ('url', models.CharField(help_text='URL de l''instance FOCUS', max_length=128, verbose_name='URL de l''instance')),
                ('users', models.ManyToManyField(blank=True, related_name='_connectorwca_users_+', related_query_name='+', to='base.ApiUser')),
            ],
            options={
                'verbose_name': 'Connecteur pour FOCUS',
            },
        ),
    ]
